apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: libp2p-relay

resources:
  - ../../deploy/kubernetes
  - namespace.yaml

patchesStrategicMerge:
  - patch.yaml


secretGenerator:
  - name: libp2p-replay-identity
    behavior: create
    files:
      - identity.key # Note: generated on-the-fly by skaffold pre-render hooks; see skaffold.yaml. 

configMapGenerator:
  - name: libp2p-replay-config
    behavior: create
    files:
      - config.json
