name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Container And Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.0.4/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
          skaffold config set --global collect-metrics false
      - name: Build docker image
        run: skaffold build --file-output=artifacts.json
      - name: Render manifests
        run: skaffold render --profile local --build-artifacts=artifacts.json --digest-source=local
